import type { WeddingConfig } from '../types';

export const weddingConfig: WeddingConfig = {
  couple: {
    partner1: 'Fernanda',
    partner2: 'Edson',
    initials: 'F&E',
  },
  event: {
    date: new Date('2026-10-02T18:00:00'),
    ceremony: {
      time: '18:00',
      venue: 'Salão do Reino das Testemunhas de Jeová',
      address: 'R. Amélia Rodrigues, 13 - Alto da Cruz, Camaçari - BA, 42800-970',
      mapsUrl: 'https://maps.app.goo.gl/kate9NACx6JkF9Ws6',
      wazeUrl: 'https://waze.com/ul?q=-23.5505,-46.6333',
    },
    reception: {
      time: '19:30',
      venue: 'Espaço Jardim das Flores',
      address: 'Av. Central, 500 - Centro, Camaçari - BA, 42800-000',
      mapsUrl: 'https://maps.app.goo.gl/example',
      wazeUrl: 'https://waze.com/ul?q=-12.6828,-38.3178',
    },
  },
  whatsapp: '5511999999999',
  heroImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80',
  gifts: [
    { id: 'g01', name: 'Cafeteira', category: 'Cozinha' },
    { id: 'g02', name: 'Jogo de lençol de casal', category: 'Quarto' },
    { id: 'g03', name: 'Aparelho de jantar', category: 'Cozinha' },
    { id: 'g04', name: 'Jogo de copos', category: 'Cozinha' },
    { id: 'g05', name: 'Faqueiro', category: 'Cozinha' },
    { id: 'g06', name: 'Jogo de panelas', category: 'Cozinha' },
    { id: 'g07', name: 'Jogo de lençol de solteiro', category: 'Quarto' },
    { id: 'g08', name: 'Travesseiros', category: 'Quarto' },
    { id: 'g09', name: 'Conjunto de tapetes para banheiro', category: 'Banheiro' },
    { id: 'g10', name: 'Jogo de pratos', category: 'Cozinha' },
    { id: 'g11', name: 'Jogo de toalha para banheiro', category: 'Banheiro' },
    { id: 'g12', name: 'Tapetes para casa', category: 'Sala' },
    { id: 'g13', name: 'Potes para mantimentos', category: 'Cozinha' },
    { id: 'g14', name: 'Mantas para sofá', category: 'Sala' },
    { id: 'g15', name: 'Panos de prato', category: 'Cozinha' },
    { id: 'g16', name: 'Toalha de mesa', category: 'Cozinha' },
    { id: 'g17', name: 'Conjunto de vasilhas plásticas', category: 'Cozinha' },
    { id: 'g18', name: 'Jarras de suco', category: 'Cozinha' },
    { id: 'g19', name: 'Liquidificador', category: 'Cozinha' },
    { id: 'g20', name: 'Pano de chão', category: 'Limpeza' },
    { id: 'g21', name: 'Garrafa de café', category: 'Cozinha' },
    { id: 'g22', name: 'Ventilador', category: 'Sala' },
    { id: 'g23', name: 'Almofadas', category: 'Sala' },
    { id: 'g24', name: 'Garrafas de água', category: 'Cozinha' },
    { id: 'g25', name: 'Fruteira', category: 'Cozinha' },
    { id: 'g26', name: 'Cortinas', category: 'Sala' },
  ],
};
